# Generated by Django 4.1.7 on 2023-03-10 08:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.IntegerField()),
                ('current_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('device_name', models.CharField(max_length=50)),
            ],
        ),
    ]
