# Generated by Django 4.1.7 on 2023-03-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=50)),
                ('device_ip', models.CharField(max_length=50)),
                ('device_id', models.CharField(max_length=50)),
                ('device_key', models.CharField(max_length=50)),
                ('device_version', models.CharField(max_length=50)),
            ],
        ),
    ]
